baseURL: https://nicholasching.netlify.app/
languageCode: en-us
title: Teen Ho Nicholas Ching's Portfolio Website 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my website.
    title: Hi, I'm Nick and this is my website :) 
  blog: {}
  contact:
    address:
      - city: London 
        country: United Kingdom
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: tching.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social: 
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/yuli.dorji/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/nickching98/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/nickching98/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/nicholasthching/
      - icon: fa-youtube
        label: Youtube
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: ''
    links:
      - name: Home
        url: ''
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: WechatIMG2.jpg
        subtitle: My life journey so far 
        title: My Bio
        url: blogs/about_me1
      - image: HK.jpg
        subtitle: From HK to LDN to MSK to ALA
        title: CV and Work Experience
        url: blogs/tempus
      - image: Squash.jpg
        subtitle: Lorem Etiam Nullam
        title: Squash and Other Interests
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "@Nicholas Ching, Made with Academic theme for Hugo"
    title: 
    url: blogs